apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lighttpd-pvc
  namespace: "eda-assets" # kpt-set: ${EDA_NAMESPACE_ASSET_HOST}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi # kpt-set: ${EDA_ASSETS_ARTIFACTS_PVC_SIZE}
