apiVersion: v1
kind: Secret
metadata:
  name: registry-docker-registry-secret
  namespace: "eda-assets" # kpt-set: ${EDA_NAMESPACE_ASSET_HOST}
  labels:
    app: docker-registry
type: Opaque
data:
  haSharedSecret: "bjhTa202Y1RjdW9QcVlITA=="
  proxyUsername: ""
  proxyPassword: ""
