apiVersion: v1
kind: ConfigMap
metadata:
  name: gogs-config
  namespace: "eda-assets" # kpt-set: ${EDA_NAMESPACE_ASSET_HOST}
data:
  app.ini: |
    BRAND_NAME = EDA
    RUN_USER = git
    RUN_MODE = prod
    [log]
    LEVEL     = info
    [repository]
    AUTO_INIT = true
    FORCE_PRIVATE = true
    [server]
    OFFLINE_MODE = true
    [database]
    TYPE = sqlite3
    [security]
    INSTALL_LOCK = true
    LOCAL_NETWORK_ALLOWLIST = *
    [auth]
    DISABLE_REGISTRATION = true
    [server]
    EXTERNAL_URL = /git
    SSH_SERVER_ALGORITHMS = ecdsa, ed25519
    MINIMUM_KEY_SIZE_CHECK = true
    [ssh.minimum_key_sizes]
    ED25519 = 256
    ECDSA   = 384
    RSA     = -1
    DSA     = -1
  readme: |-
    # {Name}

    {Description}
