apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eda-git-pv-claim
  namespace: "eda-assets" # kpt-set: ${EDA_NAMESPACE_ASSET_HOST}
  labels:
    eda.nokia.com/app: git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi # kpt-set: ${EDA_ASSETS_GIT_PVC_SIZE}
