apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: eda
  annotations:
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - '*'
allowedUnsafeSysctls:
  - '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
  - system:cluster-admins
  - system:nodes
  - system:masters
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
volumes:
  - '*'
users:
  - system:serviceaccount:metallb-system:controller
  - system:serviceaccount:metallb-system:speaker
  - system:serviceaccount:eda-system:default
  - system:serviceaccount:eda-system:fluent-bit
  - system:serviceaccount:eda-system:fluent-operator
  - system:serviceaccount:eda-system:cert-manager-csi-driver
  - system:serviceaccount:eda-system:eda-cert-checker
  - system:serviceaccount:eda-system:eda-ce
  - system:serviceaccount:eda-system:eda-asvr
  - system:serviceaccount:eda-system:eda-bsvr

